[TUDEV-12346]: AN6022 - Additional fields required for SnapScan (Platform)
ThumbzupInnovations/iso8583-jpos pull request #10
Opened 2024-03-13 16:59 UTC by monyemorathobreyden

2024-03-14 05:45 UTC, SamuelOC requested changes

2024-03-14 05:45 UTC, SamuelOC commented on src/main/java/com/thumbzup/iso8583/packager/PostBridge127Packager.java
> +        fieldMap127.put(FieldConstants.FIELD_25, new ISOMsgFieldPackager(new IFA_LLLCHAR(999, "Card Acceptor Additional Data"), new PostBridge127_49Packager()));
Should FieldConstants.FIELD_25 on line 59 not be FieldConstants.FIELD_49?

2024-03-14 07:35 UTC, monyemorathobreyden commented on src/main/java/com/thumbzup/iso8583/packager/PostBridge127Packager.java
> +        fieldMap127.put(FieldConstants.FIELD_25, new ISOMsgFieldPackager(new IFA_LLLCHAR(999, "Card Acceptor Additional Data"), new PostBridge127_49Packager()));
changed to FieldConstants.FIELD_49

2024-03-18 07:57 UTC, SamuelOC approved these changes

2024-03-18 07:57 UTC, merged